version: '2.1'

services:
    node:
      image: "node:8.9-slim"
      env_file: .env
      volumes:
          - .:/app
      working_dir: '/app'
      command: npm start
      ports:
        - 3000:3000
      depends_on:
        database:
          condition: service_healthy
  
    database:
      image: "mysql:5.6"
      env_file: .env
      restart: always
      ports:
        - 3306:3306
      healthcheck:
        test: "/etc/init.d/mysql status"
        timeout: 1s
        retries: 120